### ISSUE TITLE
File doesnot contain read-type classification. Employing pairtools

### ISSUE THREAD

**Issue by ohan-Bioinfo** [parklab/HiTea#2]
I'm implementing the tool on the cloud, but I'm having some problems. Could you explain what they are?

```
2022/11/28 10:48:48 Starting container setup.
2022/11/28 10:48:50 Done container setup.
2022/11/28 10:48:52 Starting localization.
2022/11/28 10:49:02 Localization script execution started...
2022/11/28 10:49:02 Localizing input gs://fc-00bcc31d-9daf-40fa-bca6-2c6aa332a71c/submissions/ed43243a-456f-4c23-aa8f-d9ab68f35c44/HiTea/7162fb12-ce28-4739-b4b7-27411fadbb73/call-Transposable_Element/script -> /cromwell_root/script
2022/11/28 10:49:04 Localizing input gs://fc-00bcc31d-9daf-40fa-bca6-2c6aa332a71c/NDX-22-829-004.bam -> /cromwell_root/fc-00bcc31d-9daf-40fa-bca6-2c6aa332a71c/NDX-22-829-004.bam
2022/11/28 10:51:36 Localization script execution complete.
2022/11/28 10:51:48 Done localization.
2022/11/28 10:51:55 Running user action: docker run -v /mnt/local-disk:/cromwell_root --entrypoint=/bin/bash 4dndcic/hitea@sha256:ed6f807c778fddeca22297132e9c82bed7042d24ba6c76a0fceb63a13c632f97 /cromwell_root/script


I/O and paramters:
-i --inputs /cromwell_root/fc-00bcc31d-9daf-40fa-bca6-2c6aa332a71c/NDX-22-829-004.bam
-o --outprefix ./test
-w --workdir ./here
-m --enzyme MboI
-index --index /usr/local/bin/hg38/TEConsensus_Hs.fa
-repbase --repbase /usr/local/bin/hg38/Repbase_Hs.fa
-x --wgs F
-remap --remap T
-bgAnnotations --bgAnnotations /usr/local/bin/hg38/bgRepeats_hg38.bed.gz
-chr_sizes --chrsize
-anchor_mapq --anchor_mapq 28
-clip --clip 20
-gap gap 2
-read-length inferred-readlength 98.49
-chunksize chunk size 1995M
-ncores (available) --ncores 4
-ncores (used) 4
-threads (available) 8
-threads (used) 8

command: hitea -p 4 -e MboI -q 28 -o ./test -s 20 -g hg38 -w ./here -i /cromwell_root/fc-00bcc31d-9daf-40fa-bca6-2c6aa332a71c/NDX-22-829-004.bam
sourceDirectory /usr/local/bin


Start-Time 00:00:00



# Step1 : checking dependancies ...
great!! all dependancies are present!

running pre-run checks..

1. retrieving header and chr_sizes information

2. creating background annotation files using the input file..

3. confirming TE family and subfamily names..
perl /usr/local/bin/src/prechecks.pl -index /usr/local/bin/hg38/TEConsensus_Hs.fa -polym /usr/local/bin/hg38/Polymorphs_Hs.fa -repbase /usr/local/bin/hg38/Repbase_Hs.fa -bgAnnotations ./here/bgAnnotations -enzyme MboI
(perl prechecks.pl -index /usr/local/bin/hg38/TEConsensus_Hs.fa -polym /usr/local/bin/hg38/Polymorphs_Hs.fa -repbase /usr/local/bin/hg38/Repbase_Hs.fa -bgAnnotations bgAnnotations -enzyme MboI)
L1~L1HS L1HS 6151bp
SVA~SVA_F SVA_F 1395bp
SVA~SVA_D SVA_D 1406bp
SVA~SVA_B SVA_B 1403bp
Alu~AluYb10 AluYb10 293bp
Alu~AluYk13 AluYk13 287bp
Alu~AluYb8 AluYb8 294bp
Alu~AluYb8a1 AluYb8a1 292bp
Alu~AluYb9 AluYb9 294bp
SVA~SVA_C SVA_C 1404bp
Alu~AluYa5 AluYa5 287bp
SVA~SVA_E SVA_E 1402bp
Alu~AluYb11 AluYb11 294bp
SVA~SVA_A SVA_A 1664bp

4. genrating index for TE-consensus..
[bwa_index] Pack FASTA... 0.00 sec
[bwa_index] Construct BWT for the packed sequence...
[bwa_index] 0.00 seconds elapse.
[bwa_index] Update BWT... 0.00 sec
[bwa_index] Pack forward-only FASTA... 0.00 sec
[bwa_index] Construct SA from BWT and Occ... 0.00 sec
[main] Version: 0.7.17-r1188
[main] CMD: bwa index ./here/indexC/TEConsenssus.fa
[main] Real time: 0.021 sec; CPU: 0.006 sec

5. genrating index for Repbase sequences..
[bwa_index] Pack FASTA... 0.01 sec
[bwa_index] Construct BWT for the packed sequence...
[bwa_index] 0.27 seconds elapse.
[bwa_index] Update BWT... 0.01 sec
[bwa_index] Pack forward-only FASTA... 0.01 sec
[bwa_index] Construct SA from BWT and Occ... 0.09 sec
[main] Version: 0.7.17-r1188
[main] CMD: bwa index ./here/repbase/repbase.fa
[main] Real time: 0.414 sec; CPU: 0.386 sec

6. genrating index for Polymorphic sequences..
[bwa_index] Pack FASTA... 0.00 sec
[bwa_index] Construct BWT for the packed sequence...
[bwa_index] 0.00 seconds elapse.
[bwa_index] Update BWT... 0.00 sec
[bwa_index] Pack forward-only FASTA... 0.00 sec
[bwa_index] Construct SA from BWT and Occ... 0.00 sec
[main] Version: 0.7.17-r1188
[main] CMD: bwa index ./here/indexP/Polymorph.fa
[main] Real time: 0.023 sec; CPU: 0.009 sec

pre-run checks completed successfully.


# Step2 : Splitting input file and generating fastq records ...
working on bam input (NDX-22-829-004, size: 10 Gb)
File doesnot contain read-type classification. Employing pairtools
Traceback (most recent call last):
File "/anaconda3/bin/pairtools", line 11, in <module>
sys.exit(cli())
File "/anaconda3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
return self.main(*args, **kwargs)
File "/anaconda3/lib/python3.6/site-packages/click/core.py", line 697, in main
rv = self.invoke(ctx)
File "/anaconda3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/anaconda3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/anaconda3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
return callback(*args, **kwargs)
File "/anaconda3/lib/python3.6/site-packages/pairtools/__init__.py", line 113, in wrapper
return func(*args, **kwargs)
File "/anaconda3/lib/python3.6/site-packages/pairtools/pairtools_split.py", line 46, in split
split_py(pairsam_path, output_pairs, output_sam, **kwargs)
File "/anaconda3/lib/python3.6/site-packages/pairtools/pairtools_split.py", line 109, in split_py
sam2 = cols.pop(sam2col)
IndexError: pop index out of range
Input bam file: - input is pipe/sam Use of uninitialized value $flag in numeric ge (>=) at /usr/local/bin/src/parse.pl line 137, <IN> line 3378.
at /usr/local/bin/src/parse.pl line 22, <IN> line 3378.
main::__ANON__("Use of uninitialized value \$flag in numeric ge (>=) at /usr/l"...) called at /usr/local/bin/src/parse.pl line 137
main::bam_read("-") called at /usr/local/bin/src/parse.pl line 93
Command exited with non-zero status 1
0.30user 0.17system 0:00.62elapsed 75%CPU (0avgtext+0avgdata 19112maxresident)k
0inputs+200outputs (0major+34951minor)pagefaults 0swaps
Something went wrong while parsing the input file/s. Exiting!
Completed parsing input file
Time-elapsed 00:00:05
Summary is already displayed in a log file
/usr/local/bin/hitea: line 298: ./here/./test.ReadSummary.logs: No such file or directory
Completed merging back the input parts
Time-elapsed 00:00:06


# Step3 : Extracting clusters ...
Mapping merged fastq file and extracting clusters

bwa mem -t 8 -a -v 1 -k 13 -T 20 ./here/indexC/TEConsenssus.fa ./here/./test_1.fq.gz | perl /usr/local/bin/src/find_breaks.pl -bam - -outprefix ./test_1 -wd ./here -hd ./here/headers.sam -remap T -te 1
[main] Version: 0.7.17-r1188
[main] CMD: bwa mem -t 8 -a -v 1 -k 13 -T 20 ./here/indexC/TEConsenssus.fa ./here/./test_1.fq.gz
[main] Real time: 0.001 sec; CPU: 0.002 sec
[extract_clusters=Start_Time]: 0 seconds
Input is pipein
Total number of clip read positions in the file: 0
Total badlines in the file: 0
[extract_clusters=End_Time]: 0 seconds

bwa mem -t 8 -a -v 1 -k 13 -T 20 ./here/indexP/Polymorph.fa ./here/./test_1.1.temp.remap.fq.gz | perl /usr/local/bin/src/find_breaks.pl -bam - -outprefix ./test_1 -wd ./here -hd ./here/headers.sam -remap F -te 2
[main] Version: 0.7.17-r1188
[main] CMD: bwa mem -t 8 -a -v 1 -k 13 -T 20 ./here/indexP/Polymorph.fa ./here/./test_1.1.temp.remap.fq.gz
[main] Real time: 0.001 sec; CPU: 0.002 sec
[extract_clusters=Start_Time]: 0 seconds
Input is pipein
Total number of clip read positions in the file: 0
Total badlines in the file: 0
[extract_clusters=End_Time]: 0 seconds

bwa mem -t 8 -a -v 1 -k 19 -T 30 ./here/indexC/TEConsenssus.fa ./here/./test_2.fq.gz | perl /usr/local/bin/src/find_breaks.pl -bam - -outprefix ./test_2 -wd ./here -hd ./here/headers.sam
[main] Version: 0.7.17-r1188
[main] CMD: bwa mem -t 8 -a -v 1 -k 19 -T 30 ./here/indexC/TEConsenssus.fa ./here/./test_2.fq.gz
[main] Real time: 0.001 sec; CPU: 0.002 sec
[extract_clusters=Start_Time]: 0 seconds
Input is pipein
Total number of clip read positions in the file: 0
Total badlines in the file: 0
[extract_clusters=End_Time]: 0 seconds
Completed extracting cluster locations
Time-elapsed 00:00:06
```

**Comment by ohan-Bioinfo** [comment]
can this work on exome WGS bam files, Illumina paired end
